import { jsx as _jsx } from "react/jsx-runtime";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { AuthProvider } from "./hooks/useAuth";
import "./index.css";
import "./styles/reset.css";
import App from "./App.tsx";
import ErrorBoundary from "./components/common/ErrorBoundary";
createRoot(document.getElementById("root")).render(_jsx(StrictMode, { children: _jsx(BrowserRouter, { children: _jsx(AuthProvider, { children: _jsx(ErrorBoundary, { children: _jsx(App, {}) }) }) }) }));
